name: Stats

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build:analyze

      - name: Send bundle stats to RelativeCI
        uses: relative-ci/agent-action@v3
        with:
          webpackStatsFile: ./dist/webpack-stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
